name: "Userscript Monorepo Release"
author: "LeviOP"
description: "Builds and creates releases for userscripts in a monorepo, automatically tagging on every version bump"
inputs:
  userscripts-dir:
    description: "Directory containing userscript packages"
    required: true
  setup-command:
    description: "Setup command run at the repository root to setup builds (usually installing dependencies)"
    required: false
  build-command:
    description: "Command to run at each commit checkout for each userscript package"
    required: false
  token:
    description: "GitHub token used to create releases and tags"
    default: ${{ github.token }}
runs:
  using: "node24"
  main: "dist/index.js"
